version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - mongo

volumes:
  mongo-data:
